

services:
  api:
    build: .
    command: >
      sh -c "until nc -z redis 6379; do sleep 5; done && gunicorn src.server:app --bind 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - src/config.env  

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
