services:
  api:
    build: .
    command: gunicorn src.server:app --bind 0.0.0.0:8080  
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
