name: Ride-Sharing CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        pytest
  
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t ride-sharing-backend .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag and push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/ride-sharing-backend
        
        # Tag with short SHA
        docker tag ride-sharing-backend $IMAGE_ID:${{ github.sha }}
        docker push $IMAGE_ID:${{ github.sha }}
        
        # Tag as latest
        docker tag ride-sharing-backend $IMAGE_ID:latest
        docker push $IMAGE_ID:latest