name: Ride-Sharing CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set REDIS_URL
      run: echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
    
    - name: Check Redis connection
      run: |
        sudo apt-get install -y redis-tools
        redis-cli -h localhost -p 6379 ping
    
    - name: Run tests
      run: pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t ride-sharing-backend .
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag and push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/ride-sharing-backend
        # Convert IMAGE_ID to lowercase (GitHub packages must be lowercase)
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        docker tag ride-sharing-backend $IMAGE_ID:${{ github.sha }}
        docker push $IMAGE_ID:${{ github.sha }}
        docker tag ride-sharing-backend $IMAGE_ID:latest
        docker push $IMAGE_ID:latest